import { Effect } from "effect"
import { HttpApiBuilder } from "effect/unstable/httpapi"
import { InstanceHttpApi } from "../api"
import { makeOpencodeXOperationsHandlers } from "./opencodex-operations-handlers"
import { makeOpencodeXPluginHandlers } from "./opencodex-plugin-handlers"
import { makeOpencodeXSessionHandlers } from "./opencodex-session-handlers"
import { makeOpencodeXStateHandlers } from "./opencodex-state-handlers"
import { makeOpencodeXWorkbenchFileHandlers } from "./opencodex-workbench-file-handlers"
import { makeOpencodeXWorkbenchGitHandlers } from "./opencodex-workbench-git-handlers"
import { makeOpencodeXWorkbenchGithubHandlers } from "./opencodex-workbench-github-handlers"
import { makeOpencodeXSettingsHandlers } from "./opencodex-settings-handlers"

export { sessionStatusSnapshot } from "./opencodex-session-handlers"

export const opencodexHandlers = HttpApiBuilder.group(InstanceHttpApi, "opencodex", (handlers) =>
  Effect.gen(function* () {
    const sessions = yield* makeOpencodeXSessionHandlers()
    const plugins = yield* makeOpencodeXPluginHandlers()
    const state = yield* makeOpencodeXStateHandlers(plugins)
    const files = yield* makeOpencodeXWorkbenchFileHandlers()
    const git = makeOpencodeXWorkbenchGitHandlers()
    const github = makeOpencodeXWorkbenchGithubHandlers()
    const operations = yield* makeOpencodeXOperationsHandlers()
    const settings = yield* makeOpencodeXSettingsHandlers()

    return handlers
      .handle("getSettings", settings.getSettings)
      .handle("updateSettings", settings.updateSettings)
      .handle("listProjects", sessions.listProjects)
      .handle("createProject", sessions.createProject)
      .handle("validateProject", sessions.validateProject)
      .handle("updateProject", sessions.updateProject)
      .handle("reorderProjects", sessions.reorderProjects)
      .handle("createSession", sessions.createSession)
      .handle("stateSnapshot", state.stateSnapshot)
      .handle("stateOperations", state.stateOperations)
      .handle("stateCapabilities", state.stateCapabilities)
      .handle("stateSessionCards", state.stateSessionCards)
      .handle("stateSession", state.stateSession)
      .handleRaw("stateEvent", state.stateEvent)
      .handle("updateSessionState", sessions.updateSessionState)
      .handle("moveSession", sessions.moveSession)
      .handle("removeSession", sessions.removeSession)
      .handle("removeProject", sessions.removeProject)
      .handle("listJobs", operations.listJobs)
      .handle("listPlugins", plugins.listPlugins)
      .handle("installPlugin", plugins.installPluginHandler)
      .handle("togglePlugin", plugins.togglePlugin)
      .handle("workbenchFileRead", files.workbenchFileRead)
      .handle("workbenchFileWrite", files.workbenchFileWrite)
      .handle("workbenchFileCreate", files.workbenchFileCreate)
      .handle("workbenchFileRename", files.workbenchFileRename)
      .handle("workbenchFileDelete", files.workbenchFileDelete)
      .handle("workbenchFileDiagnostics", files.workbenchFileDiagnostics)
      .handle("workbenchFileDefinition", files.workbenchFileDefinition)
      .handle("workbenchFileHover", files.workbenchFileHover)
      .handle("workbenchFileCompletion", files.workbenchFileCompletion)
      .handle("workbenchGitBranches", git.workbenchGitBranches)
      .handle("workbenchChangesPage", git.workbenchChanges)
      .handle("workbenchChangePatch", git.workbenchChangePatch)
      .handle("workbenchChangeMetricsPage", git.workbenchChangeMetricsPage)
      .handle("workbenchChangePatchPage", git.workbenchChangePatchPage)
      .handle("workbenchGitHistory", git.workbenchGitHistoryEndpoint)
      .handle("workbenchDiagnostics", git.workbenchDiagnosticsEndpoint)
      .handle("workbenchGitCheckout", git.workbenchGitCheckout)
      .handle("workbenchGitCreateBranch", git.workbenchGitCreateBranch)
      .handle("workbenchGitStage", git.workbenchGitStage)
      .handle("workbenchGitUnstage", git.workbenchGitUnstage)
      .handle("workbenchGitDiscard", git.workbenchGitDiscard)
      .handle("workbenchGitCommit", git.workbenchGitCommit)
      .handle("workbenchGitFetch", git.workbenchGitFetch)
      .handle("workbenchGitPull", git.workbenchGitPull)
      .handle("workbenchGitPush", git.workbenchGitPush)
      .handle("workbenchGitPublish", git.workbenchGitPublish)
      .handle("workbenchGitStashes", git.workbenchGitStashes)
      .handle("workbenchGitStashCreate", git.workbenchGitStashCreate)
      .handle("workbenchGitStashApply", git.workbenchGitStashApply)
      .handle("workbenchGitStashPop", git.workbenchGitStashPop)
      .handle("workbenchGitStashDrop", git.workbenchGitStashDrop)
      .handle("workbenchGithubAuth", github.workbenchGithubAuth)
      .handle("workbenchGithubRepo", github.workbenchGithubRepo)
      .handle("workbenchGithubIssues", github.workbenchGithubIssues)
      .handle("workbenchGithubPulls", github.workbenchGithubPulls)
      .handle("workbenchGithubPull", github.workbenchGithubPull)
      .handle("workbenchGithubChecks", github.workbenchGithubChecks)
      .handle("workbenchGithubCheckoutPull", github.workbenchGithubCheckoutPull)
      .handle("workbenchGithubCreatePull", github.workbenchGithubCreatePull)
      .handle("createJob", operations.createJob)
      .handle("getJob", operations.getJob)
      .handle("updateJob", operations.updateJob)
      .handle("cancelJob", operations.cancelJob)
      .handle("claimJob", operations.claimJob)
      .handle("startJob", operations.startJob)
      .handle("renewJob", operations.renewJob)
      .handle("succeedJob", operations.succeedJob)
      .handle("failJob", operations.failJob)
      .handle("retryJob", operations.retryJob)
      .handle("listGoals", operations.listGoals)
      .handle("createGoal", operations.createGoal)
      .handle("getGoal", operations.getGoal)
      .handle("planGoal", operations.planGoal)
      .handle("updateGoalPlan", operations.updateGoalPlan)
      .handle("startGoal", operations.startGoal)
      .handle("approveGoalNode", operations.approveGoalNode)
      .handle("cancelGoal", operations.cancelGoal)
      .handle("removeGoal", operations.removeGoal)
      .handle("listSwarms", operations.listSwarms)
      .handle("createSwarm", operations.createSwarm)
      .handle("getSwarm", operations.getSwarm)
      .handle("updateSwarm", operations.updateSwarm)
      .handle("cancelSwarm", operations.cancelSwarm)
      .handle("removeSwarm", operations.removeSwarm)
      .handle("addSwarmRole", operations.addSwarmRole)
      .handle("updateSwarmRole", operations.updateSwarmRole)
      .handle("listTerminalSessions", operations.listTerminalSessions)
      .handle("createTerminalSession", operations.createTerminalSession)
      .handle("getTerminalSession", operations.getTerminalSession)
      .handle("updateTerminalSession", operations.updateTerminalSession)
      .handle("openTerminalSession", operations.openTerminalSession)
      .handle("removeTerminalSession", operations.removeTerminalSession)
      .handle("listViews", operations.listViews)
      .handle("createView", operations.createView)
      .handle("reorderViews", operations.reorderViews)
      .handle("getView", operations.getView)
      .handle("updateView", operations.updateView)
      .handle("removeView", operations.removeView)
  }),
)
