import type { SessionSlashCommand, SessionSlashCommandActions } from "./session-slash-command-types"
export type { SessionSlashCommand, SessionSlashCommandActions, SessionSlashCommandContext } from "./session-slash-command-types"

export function buildSessionSlashCommands(input: {
  canRedo: boolean
  variantCount: number
  actions: SessionSlashCommandActions
}): SessionSlashCommand[] {
  return [
    {
      name: "sessions",
      title: "Switch session",
      detail: "Resume or continue an existing session",
      category: "Session",
      aliases: ["resume", "continue"],
      run: input.actions.switchSession,
    },
    {
      name: "new",
      title: "New session",
      detail: "Start a fresh chat",
      category: "Session",
      aliases: ["clear"],
      run: input.actions.createSession,
    },
    {
      name: "dashboard",
      title: "Open operations dashboard",
      detail: "Go to the OpencodeX dashboard",
      category: "OpencodeX",
      aliases: ["ops", "operations", "opencodex"],
      run: input.actions.openDashboard,
    },
    {
      name: "project",
      title: "Create project",
      detail: "Create an OpencodeX project",
      category: "OpencodeX",
      run: input.actions.createProject,
    },
    {
      name: "swarm-dash",
      title: "Show swarms",
      detail: "Open swarm dashboard entries",
      category: "Swarms",
      aliases: ["swarms", "swarm-list"],
      run: input.actions.openSwarms,
    },
    {
      name: "open-swarm",
      title: "Open swarm",
      detail: "Open the swarm management view",
      category: "Swarms",
      run: input.actions.openSwarm,
    },
    {
      name: "new-swarm",
      title: "Create swarm",
      detail: "Create a new swarm",
      category: "Swarms",
      run: input.actions.createSwarm,
    },
    {
      name: "swarm",
      title: "Use a swarm",
      detail: "Switch this session's model to an agent team",
      category: "Swarms",
      run: input.actions.useSwarm,
    },
    {
      name: "view",
      title: "Open view",
      detail: "Open the views page",
      category: "Views",
      aliases: ["views", "open-view"],
      run: input.actions.openView,
    },
    {
      name: "new-view",
      title: "Create view",
      detail: "Create a multi-session view",
      category: "Views",
      aliases: ["create-view"],
      run: input.actions.createView,
    },
    {
      name: "edit-view",
      title: "Edit view",
      detail: "Modify the active view",
      category: "Views",
      run: input.actions.editView,
    },
    {
      name: "delete-view",
      title: "Delete view",
      detail: "Remove the active view",
      category: "Views",
      run: input.actions.deleteView,
    },
    {
      name: "nsip",
      title: "New session in project",
      detail: "Create a session from a project folder",
      category: "OpencodeX",
      aliases: ["new-session-in-project"],
      run: input.actions.createProjectSession,
    },
    {
      name: "workspaces",
      title: "Manage workspaces",
      detail: "Switch or create workspaces",
      category: "Workspace",
      run: input.actions.manageWorkspaces,
    },
    {
      name: "models",
      title: "Switch model",
      detail: "Change the current composer model",
      category: "Agent",
      aliases: ["model"],
      run: input.actions.switchModel,
    },
    {
      name: "agents",
      title: "Switch agent",
      detail: "Change the current composer agent",
      category: "Agent",
      aliases: ["agent"],
      run: input.actions.switchAgent,
    },
    {
      name: "mcps",
      title: "Toggle MCPs",
      detail: "Enable or disable MCP servers",
      category: "Agent",
      aliases: ["mcp"],
      run: input.actions.toggleMcps,
    },
    {
      name: "variants",
      title: "Switch model variant",
      detail: "Choose a variant for the selected model",
      category: "Agent",
      aliases: ["variant"],
      disabled: input.variantCount === 0 ? "The selected model does not expose variants." : undefined,
      run: input.actions.switchVariant,
    },
    {
      name: "connect",
      title: "Connect provider",
      detail: "Add or configure model providers",
      category: "Provider",
      run: input.actions.connectProvider,
    },
    {
      name: "org",
      title: "Switch org",
      detail: "Change the active console organization",
      category: "Provider",
      aliases: ["orgs", "switch-org"],
      run: input.actions.switchOrg,
    },
    {
      name: "status",
      title: "View status",
      detail: "Open provider and runtime status",
      category: "System",
      run: input.actions.viewStatus,
    },
    {
      name: "themes",
      title: "Switch theme",
      detail: "Choose a TUI/GUI theme",
      category: "System",
      aliases: ["theme"],
      run: input.actions.switchTheme,
    },
    {
      name: "help",
      title: "Help",
      detail: "Show keyboard shortcuts and commands",
      category: "System",
      run: input.actions.showHelp,
    },
    {
      name: "exit",
      title: "Exit the app",
      detail: "Close OpencodeX",
      category: "System",
      aliases: ["quit", "q"],
      run: input.actions.exitApp,
    },
    {
      name: "editor",
      title: "Open editor",
      detail: "Edit the prompt in an external editor",
      category: "Prompt",
      run: input.actions.openEditor,
    },
    {
      name: "skills",
      title: "Skills",
      detail: "Insert or select a skill prompt",
      category: "Prompt",
      run: input.actions.openSkills,
    },
    {
      name: "warp",
      title: "Warp workspace",
      detail: "Change the workspace for this session",
      category: "Workspace",
      run: input.actions.warpWorkspace,
    },
    {
      name: "diff",
      title: "Open diff viewer",
      detail: "Inspect current session or git diffs",
      category: "VCS",
      run: input.actions.openDiff,
    },
    {
      name: "rename",
      title: "Rename session",
      detail: "Change the current session title",
      category: "Session",
      run: input.actions.renameSession,
    },
    {
      name: "fork",
      title: "Fork session",
      detail: "Create a new branch from a message",
      category: "Session",
      run: input.actions.forkSession,
    },
    {
      name: "compact",
      title: "Compact session",
      detail: "Summarize this session",
      category: "Session",
      aliases: ["summarize"],
      run: input.actions.compactSession,
    },
    {
      name: "undo",
      title: "Undo previous message",
      detail: "Revert to the previous user turn",
      category: "Session",
      run: input.actions.undoMessage,
    },
    {
      name: "redo",
      title: "Redo",
      detail: "Restore the reverted turn",
      category: "Session",
      disabled: input.canRedo ? undefined : "No message to redo.",
      run: input.actions.redoMessage,
    },
    {
      name: "conceal",
      title: "Toggle code concealment",
      detail: "Conceal or expand transcript code blocks",
      category: "Session",
      aliases: ["toggle-conceal", "code-conceal"],
      run: input.actions.toggleCodeConceal,
    },
    {
      name: "timestamps",
      title: "Toggle timestamps",
      detail: "Show or hide message timestamps",
      category: "Session",
      aliases: ["toggle-timestamps"],
      run: input.actions.toggleTimestamps,
    },
    {
      name: "thinking",
      title: "Toggle thinking",
      detail: "Expand or collapse reasoning blocks",
      category: "Session",
      aliases: ["toggle-thinking"],
      run: input.actions.toggleThinking,
    },
    {
      name: "actions",
      title: "Toggle tool details",
      detail: "Show or hide tool details in the transcript",
      category: "Session",
      aliases: ["tool-details", "toggle-actions"],
      run: input.actions.toggleToolDetails,
    },
    {
      name: "scrollbar",
      title: "Toggle session scrollbar",
      detail: "Show or hide the transcript scrollbar",
      category: "Session",
      aliases: ["toggle-scrollbar"],
      run: input.actions.toggleScrollbar,
    },
    {
      name: "generic-output",
      title: "Toggle generic tool output",
      detail: "Show or hide output for unknown/custom tools",
      category: "Session",
      aliases: ["generic-tool-output"],
      run: input.actions.toggleGenericToolOutput,
    },
    {
      name: "copy",
      title: "Copy session transcript",
      detail: "Copy the rendered transcript",
      category: "Session",
      run: input.actions.copyTranscript,
    },
    {
      name: "export",
      title: "Export session transcript",
      detail: "Save the rendered transcript",
      category: "Session",
      run: input.actions.exportTranscript,
    },
  ]
}
