import { HttpApi, OpenApi } from "effect/unstable/httpapi"
import { opencodexGroup } from "./opencodex-operations-group"

export {
  ClaimJobPayload,
  CompleteJobPayload,
  FailJobPayload,
  PluginListQuery,
  SessionSyncQuery,
  StartJobPayload,
  StateEventQuery,
  StateQuery,
  StateSessionCardQuery,
  StateSessionQuery,
  UpdateJobPayload,
  UpdateProjectPayload,
  UpdateSessionStatePayload,
  UpdateViewPayload,
  WorkbenchDataResult,
  WorkbenchChangeDirectory,
  WorkbenchChangeFile,
  WorkbenchChangePatch,
  WorkbenchChangePatchPage,
  WorkbenchChangePatchPageQuery,
  WorkbenchChangePatchQuery,
  WorkbenchChangeMetric,
  WorkbenchChangeMetricsPage,
  WorkbenchChangeMetricsQuery,
  WorkbenchChangeSummary,
  WorkbenchChangesPage,
  WorkbenchChangesQuery,
  WorkbenchDiagnostic,
  WorkbenchDefinitionLocation,
  WorkbenchDiagnosticsResult,
  WorkbenchFileAnalysisPayload,
  WorkbenchFileCreatePayload,
  WorkbenchFileDefinitionPayload,
  WorkbenchFileCompletionPayload,
  WorkbenchFileDeletePayload,
  WorkbenchFileDiagnosticsResult,
  WorkbenchHoverRange,
  WorkbenchHoverResult,
  WorkbenchCompletionItem,
  WorkbenchCompletionResult,
  WorkbenchFileReadQuery,
  WorkbenchFileReadResult,
  WorkbenchFileRenamePayload,
  WorkbenchFileWritePayload,
  WorkbenchGitBranches,
  WorkbenchGitBranchPayload,
  WorkbenchGitCommitPayload,
  WorkbenchGitHistoryCommit,
  WorkbenchGitHistoryFile,
  WorkbenchGitPathsPayload,
  WorkbenchGitStashCreatePayload,
  WorkbenchGitStashPayload,
  WorkbenchGithubCreatePullPayload,
  WorkbenchGithubPullPayload,
  WorkbenchOperationResult,
} from "./opencodex-schema"

export const OpencodeXApi = HttpApi.make("opencodex")
  .add(opencodexGroup)
  .annotateMerge(
    OpenApi.annotations({
      title: "opencodex",
      version: "0.0.1",
      description: "OpencodeX project and session overlay routes.",
    }),
  )
